openapi: 3.0.3
info:
  title: Diets service API
  version: 1.0.0
  description: |
    API for fetching diets and diet details.
  
    This API allows you to retrieve a list of diets, 
    each including its ID, name, picture, and description.
  
    The list endpoint does not require a request body.
  
    It supports various headers for passing request metadata.

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api
    description: Local development server

security:
  - ApiKeyAuth: []

paths:
  /diets:
    get:
      summary: Get list of diets
      operationId: listDiets
      tags:
          - Diet
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
        - $ref: 'common/header.yaml#/components/parameters/CorrelationIdHeader'
      responses:
        '200':
          description: List of diets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/listDietResponse'
              examples:
                multipleDiets:
                  summary: Example list of two diets
                  value:
                    - id: 1
                      name: "Vegetarian"
                      picture: "https://example.com/images/vegetarian-diet.jpg"
                      description: "A diet that excludes meat and fish but includes other animal products"
                    - id: 2
                      name: "Keto"
                      picture: "https://example.com/images/keto-diet.jpg"
                      description: "High-fat, low-carb diet that can help you burn fat more effectively"
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'

components:
  securitySchemes:
    ApiKeyAuth:
      $ref: 'common/security.yaml#/components/securitySchemes/ApiKeyAuth'
  schemas:
    listDietResponse:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
        picture:
          $ref: 'common/schemas.yaml#/components/schemas/Picture'
        description:
          $ref: 'common/schemas.yaml#/components/schemas/Description'