openapi: 3.0.3
info:
  title: Meal Service API
  version: 1.0.0
  description: |-
    API for fetching meals and meal details.
    This contract describes a RESTful API for a meal service.
    The API allows clients to:
      - Retrieve a list of meals, filtered by diet and optionally by category.
      - Retrieve detailed information about a specific meal by its ID.
    
    The API requires authentication via an API key provided in the X-API-Key header. 
    The contract specifies request parameters, expected responses, and data schemas for meals, diets, ingredients, allergies, and categories.

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api
    description: Local development server

security:
  - ApiKeyAuth: []

paths:
  /meals:
    get:
      summary: Get list of meals by diet ID and category ID
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
        - $ref: 'common/parameters.yaml#/components/parameters/DietIdParam'
        - $ref: 'common/parameters.yaml#/components/parameters/CategoryIdListParam'
      operationId: listMeals
      tags:
        - meal
      description: |-
        Retrieves a list of meals based on the specified diet and optional category filters.
      responses:
        '200':
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/listMealResponse'
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'

  /meal:
    get:
      summary: Get meal by ID
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
        - $ref: 'common/parameters.yaml#/components/parameters/MealIdParam'
      operationId: getMeal
      tags:
        - meal
      description: |-
          Retrieves detailed information about a specific meal by its ID.
          The response includes meal details, associated diets, ingredients, allergies, and categories.
      responses:
        '200':
          description: Meal details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readMealResponse'
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '404':
          $ref: 'common/error.yaml#/components/responses/NotFound'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'
    post:
      summary: Create meal
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
      operationId: createMeal
      tags:
        - meal
      description: |-
        To create a meal, use the createMeal endpoint and provide the meal details in the request body. 
        This will submit all necessary meal information for creation.
      requestBody:
        $ref: '#/components/requestBodies/CreateMealRequest'
      responses:
        '200':
          description: Meal created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readMealResponse'
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'
    patch:
      summary: Update meal
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
      operationId: updateMeal
      tags:
        - meal
      description: |-
        Updates an existing meal with the provided details.
        Only the fields included in the request body will be updated.
      requestBody:
        $ref: '#/components/requestBodies/UpdateMealRequest'
      responses:
        '200':
          description: Meal updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readMealResponse'
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '404':
          $ref: 'common/error.yaml#/components/responses/NotFound'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'

components:
  securitySchemes:
    ApiKeyAuth:
      $ref: 'common/security.yaml#/components/securitySchemes/ApiKeyAuth'
  requestBodies:
    CreateMealRequest:
      description: Request body for creating a new meal
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createMealRequest'
    UpdateMealRequest:
      description: Request body for updating an existing meal
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/updateMealRequest'
  schemas:
    baseMeal:
      type: object
      properties:
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
        picture:
          $ref: 'common/schemas.yaml#/components/schemas/Picture'
        description:
          $ref: 'common/schemas.yaml#/components/schemas/Description'
        recipe:
          $ref: 'common/schemas.yaml#/components/schemas/Recipe'
        servings:
          $ref: 'common/schemas.yaml#/components/schemas/Servings'
        prepTime:
          $ref: 'common/schemas.yaml#/components/schemas/PrepTime'
        calories:
          $ref: 'common/schemas.yaml#/components/schemas/Calories'
    listMealResponse:
      allOf:
        - $ref: '#/components/schemas/baseMeal'
        - type: object
          properties:
            id:
              $ref: 'common/schemas.yaml#/components/schemas/Id'
    readMealResponse:
      allOf:
        - $ref: '#/components/schemas/baseMeal'
        - type: object
          properties:
            id:
              $ref: 'common/schemas.yaml#/components/schemas/Id'
            diet:
              $ref: '#/components/schemas/DietObject'
            ingredients:
              type: array
              items:
                $ref: '#/components/schemas/IngredientObject'
            allergies:
              type: array
              items:
                $ref: '#/components/schemas/AllergyObject'
            categories:
              type: array
              items:
                $ref: '#/components/schemas/CategoryObject'
    createMealRequest:
      allOf:
        - $ref: '#/components/schemas/baseMeal'
        - type: object
          properties:
            diet:
              $ref: '#/components/schemas/DietObject'
            ingredients:
              type: array
              items:
                $ref: '#/components/schemas/IngredientObject'
            categories:
              type: array
              items:
                $ref: '#/components/schemas/CategoryObject'
    updateMealRequest:
      allOf:
        - $ref: '#/components/schemas/baseMeal'
        - type: object
          properties:
            id:
              $ref: 'common/schemas.yaml#/components/schemas/Id'
            diets:
              $ref: '#/components/schemas/DietObject'
            ingredients:
              type: array
              items:
                $ref: '#/components/schemas/IngredientObject'
            allergies:
              type: array
              items:
                $ref: '#/components/schemas/AllergyObject'
            categories:
              type: array
              items:
                $ref: '#/components/schemas/CategoryObject'
    DietObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
    IngredientObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
        amount:
          $ref: 'common/schemas.yaml#/components/schemas/Amount'
        unit:
          $ref: 'common/schemas.yaml#/components/schemas/Unit'
    AllergyObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
    CategoryObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
