openapi: 3.0.3
info:
  title: Meal Service API
  version: 1.0.0
  description: |-
    API for fetching meals and meal details.
    This contract describes a RESTful API for a meal service.
    The API allows clients to:
      - Retrieve a list of meals, filtered by diet and optionally by category.
      - Retrieve detailed information about a specific meal by its ID.
    
    The API requires authentication via an API key provided in the X-API-Key header. 
    The contract specifies request parameters, expected responses, and data schemas for meals, diets, ingredients, allergies, and categories.

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api
    description: Local development server

security:
  - ApiKeyAuth: []

paths:
  /api/meals:
    get:
      summary: Get list of meals
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
        - $ref: 'common/parameters.yaml#/components/parameters/DietIdParam'
        - $ref: 'common/parameters.yaml#/components/parameters/CategoryIdListParam'
      operationId: listMeals
      tags:
        - meal
      description: |-
        Retrieves a list of meals based on the specified diet and optional category filters.
      responses:
        '200':
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/listMealResponse'
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'

  /api/meal:
    get:
      summary: Get meal by ID
      parameters:
        - $ref: 'common/header.yaml#/components/parameters/AcceptHeader'
        - $ref: 'common/header.yaml#/components/parameters/ContentTypeHeader'
        - $ref: 'common/header.yaml#/components/parameters/RequestIdHeader'
        - $ref: 'common/header.yaml#/components/parameters/UserAgentHeader'
        - $ref: 'common/parameters.yaml#/components/parameters/MealIdParam'
      operationId: getMeal
      tags:
        - meal
      description: |-
          Retrieves detailed information about a specific meal by its ID.
          The response includes meal details, associated diets, ingredients, allergies, and categories.
      responses:
        '200':
          description: Meal details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readMealResponse'
        '400':
          $ref: 'common/error.yaml#/components/responses/BadRequest'
        '500':
          $ref: 'common/error.yaml#/components/responses/InternalServerError'

components:
  securitySchemes:
    ApiKeyAuth:
      $ref: 'common/security.yaml#/components/securitySchemes/ApiKeyAuth'
  schemas:
    listMealResponse:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
        picture:
          $ref: 'common/schemas.yaml#/components/schemas/Picture'
        description:
          $ref: 'common/schemas.yaml#/components/schemas/Description'
        recipe:
          $ref: 'common/schemas.yaml#/components/schemas/Recipe'
        prepTime:
          $ref: 'common/schemas.yaml#/components/schemas/PrepTime'
    readMealResponse:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
        picture:
          $ref: 'common/schemas.yaml#/components/schemas/Picture'
        description:
          $ref: 'common/schemas.yaml#/components/schemas/Description'
        recipe:
          $ref: 'common/schemas.yaml#/components/schemas/Recipe'
        prepTime:
          $ref: 'common/schemas.yaml#/components/schemas/PrepTime'
        diets:
          $ref: '#/components/schemas/DietObject'
        ingredient:
          type: array
          items:
            $ref: '#/components/schemas/IngredientObject'
        allergies:
          type: array
          items:
            $ref: '#/components/schemas/AllergyObject'
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryObject'
    DietObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
    IngredientObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
    AllergyObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'
    CategoryObject:
      type: object
      properties:
        id:
          $ref: 'common/schemas.yaml#/components/schemas/Id'
        name:
          $ref: 'common/schemas.yaml#/components/schemas/Name'