openapi: 3.0.3
info:
  title: Headers
  version: 1.0.0
  description: Headers just for our API's

components:
  parameters:
    AcceptHeader:
      name: Accept
      description: |
        Specifies the media type that the client is willing to receive.
        This is used to negotiate the response format.
      in: header
      required: true
      schema:
        type: string
        example: application/json
    ContentTypeHeader:
      name: Content-Type
      description: |
        Specifies the media type of the resource being sent to the server.
        This is typically used for POST and PUT requests.
      in: header
      required: false
      schema:
        type: string
        example: application/json
    RequestIdHeader:
      name: X-Request-ID
      description: |
        Unique identifier for the request, used for tracing and debugging.
        If not provided, a new UUID will be generated.
      in: header
      required: false
      schema:
        type: string
    UserAgentHeader:
      name: User-Agent
      description: |
        Identifies the client software making the request.
        This can be used for analytics or to tailor responses based on client capabilities.
      in: header
      required: false
      schema:
        type: string
        example: Mozilla/5.0
    AcceptEncodingHeader:
      name: Accept-Encoding
      description: |
        Specifies the content encoding that the client can understand.
        This is used for compression to reduce response size.
      in: header
      required: false
      schema:
        type: string
        example: gzip, deflate, br
    CorrelationIdHeader:
      name: X-Correlation-ID
      description: |
        Unique identifier for tracking requests across distributed systems.
        This helps in correlating logs and tracing requests through multiple services.
      in: header
      required: false
      schema:
        type: string
        format: uuid
        example: 123e4567-e89b-12d3-a456-426614174000
