openapi: 3.0.3
info:
  title: common schemas
  version: 1.0.0
  description: parameters just for our API's

components:
  schemas:
    Id:
      type: integer
      format: int64
      required: true
      minimum: 1
      example: 1
    Name:
      type: string
      required: true
      description: The name of the item.
      minLength: 1
      maxLength: 255
      example: Spaghetti Bolognese
    Picture:
      type: string
      maxLength: 255
      description: URL to an image representing the item.
      example: https://example.com/images/imagename.jpg
    Description:
      type: string
      description: A description of the item, providing details about its features and characteristics.
      maxLength: 255
      example: A delicious traditional Italian pasta dish with rich meat sauce, topped with fresh herbs and parmesan cheese.
    Recipe:
      type: string
      maxLength: 255
      description: Step by step instructions to prepare the item.
      example: Mix all ingredients and cook for 30 minutes.
    PrepTime:
      type: integer
      description: Preparation time in minutes
      minimum: 0
      maximum: 9999
      default: 0
      example: 30
    CreatedDate:
      type: string
      format: date
      description: Date the item was created.
      example: 2023-10-01
    NutritionalValue:
      type: number
      format: double
      minimum: 0
      maximum: 99999.99
      description: Nutritional value per 100g
      example: 25.5
