openapi: 3.0.3
info:
  title: common schemas
  version: 1.0.0
  description: parameters just for our API's

components:
  schemas:
    Id:
      type: integer
      format: int64
      minimum: 1
      example: 1
    Name:
      type: string
      minLength: 1
      maxLength: 100
      example: "Name of the item"
    Picture:
      type: string
      format: uri
      example: "https://example.com/images/salad.jpg"
    Description:
      type: string
      maxLength: 500
      example: "A diet that excludes meat and fish but includes other animal products"
    Recipe:
      type: string
      maxLength: 2000
      example: "Mix all ingredients and cook for 30 minutes."
    PrepTime:
      type: integer
      minimum: 0
    Category:
        type: object
        properties:
            id:
              $ref: '#/components/schemas/Id'
            name:
              $ref: '#/components/schemas/Name'
            description:
              $ref: '#/components/schemas/Description'
        required:
            - id
            - name
        example:
            id: 1
            name: "Vegan"
            description: "A category for vegan meals"